[package]
name = "hbt-pinboard"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
quick-xml = "0.38.0"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
